#!/usr/bin/env python

import json
import sys
from collector.classes.backdrop_json_encoder import BackdropJSONEncoder
from collector.csv_to_dictionary import csv_to_dictionary
from collector.process import process


if __name__ == '__main__':
    data = csv_to_dictionary(sys.argv[1])
    data = process(data)
    sys.stdout.write(json.dumps(data, cls=BackdropJSONEncoder))
